/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DownloadsIndexRouteImport } from './routes/downloads/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as ModelsModelIdRouteImport } from './routes/models/$modelId'
import { Route as DownloadsTaskIdRouteImport } from './routes/downloads/$taskId'
import { Route as ChatThreadIdRouteImport } from './routes/chat/$threadId'

const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsIndexRoute = DownloadsIndexRouteImport.update({
  id: '/downloads/',
  path: '/downloads/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsModelIdRoute = ModelsModelIdRouteImport.update({
  id: '/models/$modelId',
  path: '/models/$modelId',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsTaskIdRoute = DownloadsTaskIdRouteImport.update({
  id: '/downloads/$taskId',
  path: '/downloads/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/updates': typeof UpdatesRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/downloads/$taskId': typeof DownloadsTaskIdRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/chat/': typeof ChatIndexRoute
  '/downloads/': typeof DownloadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/updates': typeof UpdatesRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/downloads/$taskId': typeof DownloadsTaskIdRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/chat': typeof ChatIndexRoute
  '/downloads': typeof DownloadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/updates': typeof UpdatesRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/downloads/$taskId': typeof DownloadsTaskIdRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/chat/': typeof ChatIndexRoute
  '/downloads/': typeof DownloadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/library'
    | '/settings'
    | '/updates'
    | '/chat/$threadId'
    | '/downloads/$taskId'
    | '/models/$modelId'
    | '/chat/'
    | '/downloads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/library'
    | '/settings'
    | '/updates'
    | '/chat/$threadId'
    | '/downloads/$taskId'
    | '/models/$modelId'
    | '/chat'
    | '/downloads'
  id:
    | '__root__'
    | '/'
    | '/discover'
    | '/library'
    | '/settings'
    | '/updates'
    | '/chat/$threadId'
    | '/downloads/$taskId'
    | '/models/$modelId'
    | '/chat/'
    | '/downloads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoverRoute: typeof DiscoverRoute
  LibraryRoute: typeof LibraryRoute
  SettingsRoute: typeof SettingsRoute
  UpdatesRoute: typeof UpdatesRoute
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  DownloadsTaskIdRoute: typeof DownloadsTaskIdRoute
  ModelsModelIdRoute: typeof ModelsModelIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
  DownloadsIndexRoute: typeof DownloadsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads/': {
      id: '/downloads/'
      path: '/downloads'
      fullPath: '/downloads/'
      preLoaderRoute: typeof DownloadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/$modelId': {
      id: '/models/$modelId'
      path: '/models/$modelId'
      fullPath: '/models/$modelId'
      preLoaderRoute: typeof ModelsModelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads/$taskId': {
      id: '/downloads/$taskId'
      path: '/downloads/$taskId'
      fullPath: '/downloads/$taskId'
      preLoaderRoute: typeof DownloadsTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoverRoute: DiscoverRoute,
  LibraryRoute: LibraryRoute,
  SettingsRoute: SettingsRoute,
  UpdatesRoute: UpdatesRoute,
  ChatThreadIdRoute: ChatThreadIdRoute,
  DownloadsTaskIdRoute: DownloadsTaskIdRoute,
  ModelsModelIdRoute: ModelsModelIdRoute,
  ChatIndexRoute: ChatIndexRoute,
  DownloadsIndexRoute: DownloadsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
